"""Sales report generator — builds and saves region summaries."""

import csv
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union


def load_sales(path: Union[str, Path]) -> List[Dict[str, str]]:
    """Load sales data from a CSV file with robust path and error handling."""
    file_path = Path(path)
    if not file_path.is_file():
        raise FileNotFoundError(f"Sales data file not found: {file_path}")
    
    rows: List[Dict[str, str]] = []
    with file_path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row:
                rows.append(row)
    return rows


def summarize(rows: List[Dict[str, str]]) -> Dict[str, float]:
    """Summarize sales amounts by region with type safety and robust parsing."""
    totals: Dict[str, float] = {}
    for row in rows:
        region = row.get("region", "Unknown")
        region_str = region.strip() if region else "Unknown"
        raw_amount = row.get("amount", "0")
        try:
            amount = float(raw_amount) if raw_amount is not None else 0.0
        except (ValueError, TypeError):
            amount = 0.0
        totals[region_str] = totals.get(region_str, 0.0) + amount
    return totals


def top_region(totals: Dict[str, float]) -> Optional[str]:
    """Return the region with the highest sales."""
    if not totals:
        return None
    best: Optional[Tuple[str, float]] = None
    for region, amount in totals.items():
        if best is None or amount > best[1]:
            best = (region, amount)
    return best[0] if best else None


def format_report(totals: Dict[str, float], generated_by: str = "system") -> str:
    """Format sales summary totals into a textual report."""
    lines = ["SALES REPORT", "============"]
    for region in sorted(totals):
        lines.append(f"{region:>12}: {totals[region]:.2f}")
    lines.append(f"Generated by {generated_by} on {datetime.now():%Y-%m-%d}")
    return "\n".join(lines)


def save_report(report: str, path: Union[str, Path] = "report.txt") -> None:
    """Save the generated report string to a file."""
    file_path = Path(path)
    file_path.write_text(report + "\n", encoding="utf-8")


if __name__ == "__main__":
    pass