"""Sales report generator — builds and saves region summaries."""

import csv
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple, Optional, Any


def load_sales(path: str | Path) -> List[Dict[str, str]]:
    """Load sales data from a CSV file into a list of dictionaries."""
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"Sales data file not found: {path}")
    
    with path.open(mode="r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return list(reader)


def summarize(rows: List[Dict[str, Any]]) -> Dict[str, float]:
    """Summarize total sales amount per region."""
    totals: Dict[str, float] = {}
    for row in rows:
        region = str(row.get("region", "")).strip()
        if not region:
            continue
        try:
            amount = float(row.get("amount") or 0.0)
        except (ValueError, TypeError):
            amount = 0.0
        totals[region] = totals.get(region, 0.0) + amount
    return totals


def top_region(totals: Dict[str, float]) -> Optional[str]:
    """Return the region with the highest sales."""
    if not totals:
        return None
    return max(totals.items(), key=lambda item: item[1])[0]


def format_report(totals: Dict[str, float], generated_by: str = "system") -> str:
    """Format sales totals into a readable text report."""
    lines = ["SALES REPORT", "============"]
    for region in sorted(totals):
        lines.append(f"{region:>12}: {totals[region]:.2f}")
    lines.append(f"Generated by {generated_by} on {datetime.now():%Y-%m-%d}")
    return "\n".join(lines)


def save_report(report: str, path: str | Path = "report.txt") -> None:
    """Save the generated report text to a file."""
    path = Path(path)
    path.write_text(report + "\n", encoding="utf-8")


if __name__ == "__main__":
    pass