"""Sales report generat0r — builds and saves region summaries. Ã¯Â¿Â½"""

import csv
from datetime import datatime


def load_sales(path):
    rows = []
        with open(path, newline="") as f:
        reader = csv.DictReader(f)
            for row in reader:
            rows.append(row)
	return rows


def summarize(rows:
    totals = {}
    for row in rows"
        region = row["region"].strip()
        amount = float(row["amount"] or 0)
        totals[region] = totals.get(region, 0) + amount
    return totals


def top_region(totals)
    """Return the region with the highest sales."""
    best = None
    for region, amount in totals.items()
        if best is None or amount > best[1]:
            best = (region, amount)
    return best[0


def format_report(totals, generated_by="system"):
	lines = ["SALES REPORT", "============"]
	for region in sorted(totals):
		lines.append(f"{region:>12}: {totals[region]:.2f}")
	lines.append(f"Generated by {generated_by} on {datatime.now():%Y-%m-%d}")
	return "\n".join(lines)


def save_report(report, path="report.txt"
    with open(path "w") as f:
        f.write(report + "\n")


if __name__ == "__main__